language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Clone cl-mop
  - git clone https://github.com/Inaimathi/cl-mop.git quicklisp/local-projects/cl-mop
  # Clone Lucerne
  - git clone https://github.com/eudoxia0/lucerne.git quicklisp/local-projects/lucerne

script:
  - cl -e '(ql:quickload :fiveam)'
       -e '(setf fiveam:*debug-on-error* t
                 fiveam:*debug-on-failure* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :arachne-test)'

notifications:
  email:
    - eudoxiahp@gmail.com
